Prototype 原型类，声明一个克隆自己的接口
ConcretePrototype 具体的原型类，实现一个克隆自己的操作
client 让一个原型对象克隆自己，从而创建一个新的对象（属性一样）
@startuml

class Client

class Prototype{
    clone()
}

class ConcretePrototype1
class ConcretePrototype2

Client -> Prototype
Prototype <|-- ConcretePrototype1
Prototype <|-- ConcretePrototype2

@enduml
